name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: false

jobs:
  pit:
    name: Mutation Testing (PIT)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/gradle-bootstrap
      - uses: gradle/actions/setup-gradle@v4
      - name: Run PIT
        run: |
          chmod +x ./gradlew
          ./gradlew --no-daemon pitest

      - name: Upload PIT reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pit-reports
          path: |
            **/build/reports/pitest
            build/reports/pitest
          if-no-files-found: warn
          retention-days: 14

  depcheck:
    name: depcheck + sbom
    runs-on: ubuntu-latest
    needs: security_changes
    timeout-minutes: 30
    env:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
    steps:
      - uses: actions/checkout@v5
      - name: Gradle wrapper + JDK
        uses: ./.github/actions/gradle-bootstrap
      - uses: gradle/actions/setup-gradle@v4
      - name: Cache Dependency-Check data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: ${{ runner.os }}-dc-data-${{ hashFiles('gradle/libs.versions.toml') }}
          restore-keys: |
            ${{ runner.os }}-dc-data-
      - name: Security gate (aggregate + SBOM)
        run: ./gradlew securityGate --stacktrace
      - name: Upload depcheck & SBOM
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: depcheck-sbom
          path: |
            **/build/reports/dependency-check-report.*
            **/build/reports/bom.*
          if-no-files-found: ignore
          retention-days: 14
