name: CI

on:
  pull_request:

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: .github/filters.yaml

  inspect:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - name: Print raw JSON
        run: echo "filters=${{ needs.changes.outputs.modules }}"
      - name: Pretty print + count
        env:
          FILTERS: ${{ needs.changes.outputs.filters }}
        run: |
          echo "$FILTERS" | jq -r .
          echo "count: $(echo "$FILTERS" | jq -r 'length')"


  spotless:
    needs: changes
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Gradle wrapper + JDK
        uses: ./.github/actions/gradle-bootstrap
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew spotlessCheck --stacktrace

  quality:
    name: quality • ${{ matrix.module }}
    runs-on: ubuntu-latest
    needs: [changes, spotless]
    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}
    steps:
      - uses: actions/checkout@v5
      - name: Gradle wrapper + JDK
        uses: ./.github/actions/gradle-bootstrap
      - uses: gradle/actions/setup-gradle@v4
      - name: Unit + JaCoCo
        run: ./gradlew :${{ matrix.module }}:jacocoTest --stacktrace
      - name: Upload unit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: tests-${{ matrix.module }}
          path: ${{ matrix.module }}/build/reports/tests/test/**/*
          if-no-files-found: ignore
      - name: Upload JaCoCo reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-${{ matrix.module }}
          path: |
            ${{ matrix.module }}/build/reports/jacoco/test/**/*
            ${{ matrix.module }}/build/jacoco/**/*
          if-no-files-found: ignore

  archtests:
    name: architecture-tests
    runs-on: ubuntu-latest
    needs: spotless
    steps:
      - uses: actions/checkout@v5
      - name: Gradle wrapper + JDK
        uses: ./.github/actions/gradle-bootstrap
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew :modules:architecture-tests:test --stacktrace
      - name: Upload ArchUnit reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: archtests
          path: modules/architecture-tests/build/reports/tests/test/**/*
          if-no-files-found: ignore
