name: test-pr

on:
  pull_request:
    branches: [ main ]
    paths:
      - '**.java'
      - 'build.gradle*'
      - 'settings.gradle*'
      - 'gradle/**'
  push:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  JACOCO-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Java&Gradle Setup
        uses: ./.github/actions/gradle-bootstrap
      - name: Build with Gradle and generate JaCoCo report
        run: ./gradlew --no-daemon jacocoTest
      - name: Upload JaCoCo report artifact
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: build/reports/jacoco/test/html

  PIT-PR:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
      - name: Java&Gradle Setup
        uses: ./.github/actions/gradle-bootstrap
      - name: PIT
        run: ./gradlew --no-daemon pitest
      - name: Upload PIT report
        uses: actions/upload-artifact@v4
        with:
          name: pitest-report
          path: build/reports/pitest

